#!/bin/bash

trash_dir="/trash"
mkdir -p "$trash_dir"

files_to_trash=()
use_real_rm=false
force=false

for arg in "$@"; do
    case "$arg" in
        --help|--version) use_real_rm=true; break ;;
        -f|--force) force=true ;;
        -i|-v|-I|--interactive|--verbose) continue ;;
        -r|-R|--recursive) continue ;;
        -*) use_real_rm=true; break ;;
        *) files_to_trash+=("$arg") ;;
    esac
done

if [ "$use_real_rm" = true ] || [ ${#files_to_trash[@]} -eq 0 ]; then
    /bin/rm "$@"
else
    for file in "${files_to_trash[@]}"; do
        if [ ! -e "$file" ]; then
            [[ "$force" == false ]] && echo "rm: cannot remove '$file': No such file or directory"
            continue
        fi

        # OPTIMIZATION: Use Bash built-in parameter expansion instead of 'basename'
        # ${file##*/} strips everything up to the last /
        base_name="${file##*/}"
        
        if [ -e "$trash_dir/$base_name" ]; then
            random_suffix=$(mktemp -u XXXXXXXXXXXX)
            mv "$file" "$trash_dir/${base_name}-${random_suffix}"
        else
            mv "$file" "$trash_dir/"
        fi
    done
fi
